name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        component: [ssm-env, ssm-secrets-webhook]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker
        uses: docker/build-push-action@v1
        with:
          repository: pwillie/${{ matrix.component }}
          dockerfile: Dockerfile.${{ matrix.component }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          tag_with_ref: true
